#!/data/data/com.termux/files/usr/bin/bash

aaptVariant=aapt2_64

if ! command -v qemu-x86_64 &> /dev/null; then
    echo "qemu-x86_64 is not installed. Please install it to use this wrapper."
    exit 1
fi

aaptDir=/data/data/com.termux/files/usr/bin/apktool-cli/aapt

BINARY="$aaptDir/$aaptVariant"

if [ ! -f "$BINARY" ]; then
    echo ""$BINARY" not found in the script's directory."
    exit 1
fi

exec qemu-x86_64 "$BINARY" "$@"
